---
title: "Birds"
author: "Fiona Price"
date: "2025-04-01"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library( ape )
library( plotrix )
library(dplyr)
library(here)
load("/home/guest/ENVIRON623/Data/birdData2025.rdata", verbose = "T")
source("/home/guest/ENVIRON623/Data/captureRecaptureFunctions (2).R")
source("/home/guest/ENVIRON623/Data/scr.stg.1.R")
source("/home/guest/ENVIRON623/Data/clarkFunctions2025 (4).R")
library(foreach)
library(doParallel)
```

```{r}
detect <- .67
eIn    <- round( pi*2500 )                       # area for in and out
eOut   <- round( pi*10000 ) - eIn                # counted in are not included in out
effort <- round( (eIn + detect*eOut)/10000, 4 ) 
```

```{r Species Rank Abundance}
specMean <- colMeans( ydata/effort, na.rm = T )
specMean <- specMean[ order( specMean, decreasing = T ) ]
n <- 10                                                    # label only abundant spp

par( mfrow = c(1,2), bty = 'n', omi = c(.2,.4,.1,.1) )
plot( specMean, type = 's', las = 1, xlab = '', ylab = '' )
text( 1:n, specMean[ 1:n ], names( specMean )[1:n], pos = 4, cex = (1:n)^-.3 )
title( 'CPE' )

plot( specMean, type = 's', log = 'xy', las = 1, xlab = '', ylab = '' )
title( 'log scale' )

xloc <- sqrt( c(1:n)*(2:(n+1)) )
text( xloc, .9*specMean[1:n], names( specMean )[1:n], srt = 90, pos = 2, cex = (1:n)^-.4 )
mtext( 'Rank', 1, outer = T )
mtext( 'Abundance', 2, outer = T )
```

```{r NMDS}
library( MASS )
pvars <- c('tpi', 'ph')
ycov  <- cov( cbind( xdata[, pvars ], ydata ) ) # species by species covariance
ydist <- cov2Dist( ycov )

# find and remove redundant species
ylower <- ydist
ylower[ upper.tri( ylower, diag = T ) ] <- Inf
zeros <- which( ylower == 0, arr.ind = T )
ydist  <- ydist[ -zeros[,1], -zeros[,1] ]

# NMDS
tmp <- isoMDS( ydist, k = 3)


eVecs  <- tmp$points
colnames(eVecs) <- paste('NMDS',c(1:3),sep = '_')

# plot first 2 eigenvectors with most abundant species
par(mfcol=c(1, 2), bty='n', mar=c(2,4,1,3), omi = c( .6, .1, .1, .1), xpd = T)
sn <- names( specMean )[ 1:5 ]

plot( eVecs[,1], eVecs[,2], cex=1, pch=16, xlab = 'axis 1', ylab = 'axis 2',
      xaxt = 'n' ) 
abline(h=0,col=.getColor('black',.3),lwd=2,lty=2)
abline(v=0,col=.getColor('black',.3),lwd=2,lty=2)
points( eVecs[ pvars, 1], eVecs[ pvars, 2 ], pch = 16, col = 'brown', cex = 1.1 )
text( eVecs[ pvars, 1], eVecs[ pvars, 2 ], pvars, pos = 3, col = 'brown', cex = 1.1 )
text( eVecs[ sn, 1], eVecs[ sn, 2 ], sn, pos = 2, col = 'darkgreen', cex = .7 )

plot( eVecs[,1], eVecs[,3], cex=1, pch=16, xlab = 'axis 1', ylab = 'axis 3') 
abline(h=0,col=.getColor('black',.3),lwd=2,lty=2)
abline(v=0,col=.getColor('black',.3),lwd=2,lty=2)
points( eVecs[ pvars, 1], eVecs[ pvars, 3 ], pch = 16, col = 'brown', cex = 1.1 )
text( eVecs[ pvars, 1], eVecs[ pvars, 3 ], pvars, pos = 3, col = 'brown', cex = 1.1 )
text( eVecs[ sn, 1], eVecs[ sn, 3 ], sn, pos = 2, col = 'darkgreen', cex = .7 )

# repeat for plots (plot x plot )
xcov  <- cov( t( ydata/effort ) )
xdist <- cov2Dist( xcov )
xlower <- xdist
xlower[ upper.tri( xlower, diag = T ) ] <- Inf
zeros <- which( xlower == 0 | is.na( xlower ), arr.ind = T )
xdist  <- xdist[ -zeros[,1], -zeros[,1] ]

tmp <- isoMDS( xdist , k = 3)


xvecs  <- tmp$points
colnames(xvecs) <- paste('NMDS',c(1:3),sep = '_')

# label habitat
col <- rep( 'blue', nrow( xvecs ) )
col[ grep( 'Gran', rownames( xvecs ) ) ] <- 'grey' 

par( mfrow = c(1,2), bty = 'n', omi = c(.2,.4,.1,.1) )
plot( xvecs[,1], xvecs[,2], cex=1, pch=16, xlab = 'axis 1', ylab = 'axis 2',
      xaxt = 'n', col = col, xlim = c(-1,1) ) 
abline(h=0,col=.getColor('black',.3),lwd=2,lty=2)
abline(v=0,col=.getColor('black',.3),lwd=2,lty=2)

plot( xvecs[,1], xvecs[,3], cex=1, pch=16, xlab = 'axis 1', ylab = 'axis 3', col = col) 
abline(h=0,col=.getColor('black',.3),lwd=2,lty=2)
abline(v=0,col=.getColor('black',.3),lwd=2,lty=2)
legend( 'bottomright', c( 'riparian', 'granites' ), text.col = c( 'blue', 'grey' ),
        bty = 'n')
```


```{r Joint species abundance}
library( gjam )
trim <- gjamTrimY( ydata, minObs = 5, OTHER = F )
y    <- trim$y                                         # trimmed to spp that occur 5 times
e <- effort[, trim$colIndex ]                             # matching effort columns


xdata$habitat <- as.factor( xdata$habitat )
form <- as.formula( ~ tpi + habitat )


effort <- list( columns = 1:ncol( y ), values = e )
ml     <- list(ng = 5000, burnin = 2000, typeNames = 'DA', effort = effort )
out    <- gjam( formula = form, xdata, ydata = y, modelList = ml)

summary( out )

trophic    <- sbyt[ colnames(y), 'TrophicNiche' ]
specNames <- colnames( y )
specColor <- rep('black',ncol(y))
specColor[ trophic == 'Frugivore' ] <- '#d95f02'
specColor[ trophic == 'Granivore' ]  <- '#377eb8'
specColor[ trophic == 'Invertivore' ]  <- 'red'

names( specColor ) <- trophic
gjamPlot( out, list( PLOTALLY = T, GRIDPLOTS = T, specColor = specColor ) )
```

```{r}
tnames <- c( "BeakWidth", "WingLength", "Mass", "Habitat", "Migration",  "TrophicNiche" )

xdata$habitat <- as.factor( xdata$habitat )

# exclude missing traits
wna <- which( is.na( sbyt ), arr.ind = T )
wna <- unique( wna[,1] )
y <- y[, -wna ]
effort$columns <- effort$columns[ -wna ]
effort$values  <- effort$values[ ,-wna ]

sbyt   <- sbyt[ colnames(y), ]
sbyt$Migration <- as.factor( sbyt$Migration )         # declare factors
sbyt$Habitat   <- as.factor( sbyt$Habitat )
sbyt$TrophicNiche <- as.factor( sbyt$TrophicNiche )

ttypes <- c('CA', 'CA', 'CA', 'CAT', 'CAT', 'CAT' )  # variable types for traits

tmp <- gjamSpec2Trait(y, sbyt, ttypes)
tTypes      <- tmp$traitTypes                  # M = 15 values
u           <- tmp$plotByCWM                   # n X M
specByTrait <- tmp$specByTrait                 # S X M
M           <- ncol(u)
n           <- nrow(u)

ml  <- list(ng = 3000, burnin = 500, typeNames = tTypes )
out <- gjam( form, xdata = xdata, ydata = u, modelList = ml)

tnames <- colnames(u)
sc <- rep( 'black', M)                                  # highlight types
wo <- grep( 'Habitat', tnames )     
wf <- grep( "TrophicNiche", tnames )                             
wm <- grep( "Migration", tnames )

sc[wo] <- '#f46d43'
sc[wf] <- '#005a32'
sc[wm] <- '#253494'
names( sc ) <- rep('size', M )
names(sc)[ wo ] <- 'habitat'
names(sc)[ wf ] <- 'trophic'
names(sc)[ wm ] <- 'migration'

pl  <- list(GRIDPLOTS = TRUE, PLOTALLY = T, specColor = sc)
gjamPlot(output = out, plotPars = pl)

```
