---
title: "Climate at KNP"
author: "Fiona Price"
date: "2025-02-06"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(dplyr)
library(here)

source("/Users/fionaprice/ENVIRON623/Data/clarkFunctions2025.R")
load("/Users/fionaprice/ENVIRON623/Data/annualClimateKruger.rdata", verbose = T)
load("/Users/fionaprice/ENVIRON623/Data/monthlyClimateKruger.rdata", verbose = T )
load("/Users/fionaprice/ENVIRON623/Data/herbivoreCensus.rdata", verbose = T )
```

```{r}
sapply( substratePoly, dim )
head( substratePoly[[1]], 4 ) 

# map limits
xlim <- c( 30.8, 32.1 )
ylim <- c( -25.6, -22.2 )

# sector colors, names
sectCols <- c('#003c30','#8dd3c7','#bebada','#fb8072','#80b1d3',
              '#fdb462','#b3de69','#b15928')
sectors  <- substrateData$sector                     

# draw map, add legend
polyMap( polyList = substratePoly, type = substrateData$sector,
         xaxt = 'n', yaxt = 'n', border = sectCols, col = sectCols )
legend( 'topright', legend = sectors, text.col = sectCols, bty = 'n' )
```

```{r}
xlim <- c( 30.8, 32.1 )
ylim <- c( -25.6, -22.2 )

# sector colors
sramp    <- c('#003c30','#8dd3c7','#bebada','#fb8072','#80b1d3',
              '#fdb462','#b3de69','#b15928')
sectors  <- substrateData$sector                     # sector names
nsect    <- length( sectors )                 
sectCols <- colorRampPalette( sramp[-1] )( nsect )   # interpolated ramp
names( sectCols ) <- sectors
```

```{r}
subs  <- unique( substrateData$substrate )        
scols <- sramp[ c(1, nsect) ]

polyMap( polyList = substratePoly, type = substrateData$substrate,
         border = scols, xaxt = 'n', yaxt = 'n', col = scols, add = F )
axis(1, at = c( 31, 32 ) )
axis(2, at = c(-25, -24, -23), pos = 30.7, las = 1 )
legend( 'topright', legend = subs, text.col = scols, bty = 'n' )
title( 'Substrate' )
```

```{r}
par( mfrow=c(1,2), bty = 'n', omi = c(.1,.1, .3, .4 ) )
siteTemp <- rowMeans( annualTemp, na.rm = T )   # climate mean by location

nlev <- 20
tfun <- colorRampPalette( rev( colRed2Blu ) ) # assign colors to climate gradients

# map climate
imageMap( lonLat, siteTemp, colRamp = tfun(nlev), xaxt = 'n', yaxt = 'n', xlim = xlim, ylim = ylim )
polyMap( polyList = substratePoly, type = substrateData$substrate, border = 'grey', lwd = 2, add = T )
title( 'Temperature' )

colorScaleLegend( xleg = c( 33, 33.3), yleg = c( -23, -22 ), zlim = round( range(siteTemp) ), 
                  xlim = xlim, ylim = ylim, ncol = nlev, units = '', colorRamp = tfun(nlev) ) 
```

```{r}
siteDef <- rowMeans( annualDef, na.rm = T )
dfun    <- colorRampPalette( rev( colBrown2Green ) )

imageMap( lonLat, siteDef, colRamp = dfun(nlev),
          xlim = xlim, ylim = ylim, zlim = c(-900, 900), xaxt = 'n', yaxt = 'n' )
polyMap( polyList = substratePoly, type = substrateData$substrate, border = 'grey', lwd = 2, add = T )
title( 'Moisture deficit' )

colorScaleLegend( xleg = c( 33, 33.3), yleg = c( -23, -22 ), zlim = c(-900, 900), 
                  xlim = xlim, ylim = ylim, ncol = nlev, 
                  units = 'mm', colorRamp = dfun(nlev) ) 

```

```{r}
lnames  <- c('lon','lat')
locs    <- rbind( c( 30.86, -25.2 ), c( 31.22513, -22.73519 ), c( 31.55659, -24.97129 ) ) 
dimnames( locs ) <- list( c( 'Thaba Chweu',  'Collins Chabane', 'Skukuza' ), c('lon','lat') )
```

```{r}
polyMap( polyList = substratePoly, type = substrateData$substrate,
         col = scols, xaxt = 'n', yaxt = 'n' )
points( locs[,1], locs[,2], pch = 16, col = 'white', cex = 1.4 )
points( locs[,1], locs[,2], pch = 16, col = 'black', cex = 1. )
text( locs[,1], locs[,2], rownames(locs), pos = 2 )
```

```{r}
load("/Users/fionaprice/ENVIRON623/Data/monthlyClimateKruger.rdata", verbose = T)

mm    <- RANN::nn2( lonLat, locs, k = 1 )[[1]] # grid closest to three locations
nsite <- nrow(locs)
ll    <- lonLat[mm,]
```

```{r}
yrMonth <- columnSplit( colnames( prec ), '_' )
year    <- as.numeric( yrMonth[,1] )
month   <- as.numeric( yrMonth[,2] )
yindex  <- rep( year, each = nrow(ll) )        # yr index repeated for number of sites (rows in ll)
sindex  <- rep( rownames( ll ), ncol( prec ) ) # site index repeated for number of YEAR_MO's

P   <- tapply( as.vector( prec[ rownames(ll),] ), list( sindex, yindex ), sum )
PET <- tapply( as.vector( pet[ rownames(ll),] ), list( sindex, yindex ), sum )
D   <- PET - P
```

```{r}
mindex <- rep( month, each = nrow(ll) )  # month index repeated for number of sites
P   <- tapply( as.vector( prec[ rownames(ll),] ), list( sindex, mindex ), mean )
PET <- tapply( as.vector( pet[ rownames(ll),] ), list( sindex, mindex ), mean )
D   <- PET - P
```

```{r}
prec1 <- prec[ rownames(ll),]
pet1  <- pet[ rownames(ll),]
rownames(prec1) <- rownames(pet1) <- rownames(locs)

par( mfrow = c(1,3), bty = 'n', mar = c( 3, 2, 4, 1), omi = c(.4,.5, .1, .1) )
wideFormat2waterBalance( prec1, pet1, years = c(2011:2020), ylim = c(0, 150),
                         ylab = '', yaxt = c('s', rep('n', (nsite-1)) ) )
mtext( 'Month', 1, line = 1, outer = T, cex = 1.2 )
mtext( 'P, PET (mm)', 2, line = 1, outer = T, las = 0, cex = 1.2 )
```

```{r}
mm <- RANN::nn2( lonLat, substrateData[,c('lon','lat')], k = 1 )[[1]]
sectTemp <- annualTemp[mm,]
sectDef  <- annualDef[mm,]
yr   <- as.numeric( colnames( sectTemp ) )
xlim <- range( yr )

# temperate series by sector
par( mfrow = c(1,2), bty = 'n', mar = c(4,4,1,1), omi = c(.5, .1, .1, .1) )
ylim <- range( sectTemp )

plot( NA, xlab = '', ylab = 'Degrees C', xlim = xlim, ylim = ylim, las = 1 )
for( k in 1:nsect){
  lines( yr, sectTemp[k,], col = sectCols[k], lwd = 2 )
  shadeThreshold( yr, sectTemp[k,], tmin = mean( sectTemp[k,] ), 
                  border = sectCols[k], col = .getColor( sectCols[k], .4) )
}
title( 'Temperature' )

# moisture deficit
ylim <- range( sectDef )
plot( NA, xlab = '', ylab = 'mm', xlim = xlim, ylim = ylim, las = 1  )
for( k in 1:nsect){
  lines( yr, sectDef[k,], col = sectCols[k], lwd = 2 )
  shadeThreshold( yr, sectDef[k,], tmin = mean( sectDef[k,] ), 
                  border = sectCols[k], col = .getColor( sectCols[k], .4) )
}
title( 'Moisture Deficit' )
mtext( 'Year', 1, outer = T, cex = 1.5 )
```

```{r}
floods   <- c(2000, 2022, 2022)
droughts <- c( 1970, 1983, 1987, 1992, 2015, 2016, 2019 )
segments( floods, floods*ylim[1], floods, sectDef[k, as.character(floods) ],
          lwd = 1.5, col = 'blue', lty = 2 )
segments( droughts, droughts*ylim[2], droughts, sectDef[k, as.character(droughts) ],
          lwd = 1.5, col = 'orange', lty = 2 )
```
